var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-10586344-1'],
['_setDomainName', '.mbaobao.com'],
['_setAllowHash', false],
['_addOrganic', 'baidu', 'word'],
['_addOrganic', 'soso', 'w'],
['_addOrganic', '3721', 'name'],
['_addOrganic', 'yodao', 'q'],
['_addOrganic', 'vnet',  'kw'],
['_addOrganic', 'sogou', 'query'],
['_addIgnoredOrganic', '麦包包'],
['_addIgnoredOrganic', 'mbaobao'],
['_addIgnoredOrganic', 'www.mbaobao.com'],
//['_setVar', _ga_username],
['_trackPageview']);
