var passport=(function(){var SERVER_PATH="http://login.mbaobao.com/check.html";var TIMEOUT=10000;var USERNAME_MAX_LENGHT=50;var REG_EMAIL=/^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$/i;var _opt={skin:"http://wsstatic.mbaobao.com/v5/js/passport/passport_skin.css",width:450,closeClass:".span_close",titleClass:".span_opentitle",contentClass:".mbbpspt_opencont",title:"您尚未登录"};var api;var _pop,_popContent,_mask;var _checked=false;var _lang=["Email格式不正确","用户名不能为空","密码不能为空","验证码不能为空","抱歉！服务出了点问题。","密码两次输入不一致","验证密码不能为空","此用户名已经注册过","用户名太长了"];var _refererUrl=encodeURIComponent(location.href);var _isIE6=!-[1,]&&!window.XMLHttpRequest;$(function(){$("head").append('<link rel="stylesheet" type="text/css" href="'+_opt.skin+'" media="all"/>');var html=document.getElementsByTagName('html')[0];if(_isIE6&&document.body.currentStyle.backgroundAttachment!=='fixed'){html.style.backgroundImage='url(about:blank)';html.style.backgroundAttachment='fixed';}});function _checkLogin(callBack){if(typeof(callBack)!=="function"){callBack=function(){};}
if(api.user!==null){callBack(true);return;}else if(_checked){callBack(false);return;}
$.ajax({"type":"GET","url":SERVER_PATH,"dataType":"jsonp","timeout":TIMEOUT,"data":{"do":"checklogin"},"success":function(json){if(json.success===0){callBack(false);}else if(json.success===1){api.user=json.data;callBack(true);}
_checked=true;},"error":function(){alert("服务不可用!");}});}
function _checkEmail(email,callBack){if(typeof(callBack)!=="function"){callBack=function(){};}
$.ajax({"type":"GET","url":SERVER_PATH,"dataType":"jsonp","timeout":TIMEOUT,"data":{"do":"checkemail","email":email},"success":function(json){if(json.success===0){callBack(false);}else if(json.success===1){callBack(true);}},"error":function(){alert("服务不可用!");}});}
function popLogin(callBack){var formData={"ready":true,"data":{"do":"login","email":"","pw":"","verifycode":"","hidden_unique":""}};var template='<form action="#"method="POST"name="loginForm"class="loginForm"><fieldset id="open_loginbox"class="open_regloginbox"><p class="pspt_back_msg"></p><p class="p_item"><label class="itemtitle">Email：</label><input type="text"class="txt"id="loginEmail"name="email"tabindex="1"/><span id="span_loginEmail"class="pspt_msg"></span></p><p class="p_item"><label class="itemtitle">密码：</label><input type="password"class="txt"id="loginPassword"name="password"tabindex="2"/><a href="http://www.mbaobao.com/user/get_password.php"target="_blank"class="c_g">忘记密码？</a><span id="span_loginPassword"class="pspt_msg"></span></p><p class="p_item"><label class="itemtitle">验证码：</label><input class="txt"type="text"autocomplete="off"id="loginVerifycode"name="verifycode"style="width:65px;"maxlength="4"tabindex="3"/><span id="login_verifycode_img"></span>&nbsp;<a href="#"class="c_b refresh_vcode">换一张</a>&nbsp;<span id="span_loginVerifycode"class="pspt_msg"></span></p><p class="p_item p_btn"><input type="submit"class="btn login_but"name="btn_submit"value="登 录"tabindex="4"/><span>新用户？&nbsp;<a href="#" class="c_r go_register_pop">立即注册</a></span></p>'+'<div class="open_otherlogin"><h4 class="h4_otherlogin">使用合作网站账号登录麦包包：</h4><p><a class="a_login_zfb" href="http://www.mbaobao.com/user/passport.php?id=200&referer_url={refererUrl}"tabindex="5">使用支付宝账号登录</a><a class="a_login_139" href="http://www.mbaobao.com/user/passport.php?id=5"tabindex="6">使用139邮箱登录</a><a class="a_login_weibo"href="http://www.mbaobao.com/user/passport.php?id=25"tabindex="7">使用新浪微博登录</a></p></div></fieldset></form>';template=template.replace("{refererUrl}",_refererUrl);var dom=$(document.createElement("div")).hide().html(template);var f_email=dom.find("#loginEmail");var f_pw=dom.find("#loginPassword");var f_vcode=dom.find("#loginVerifycode");var form_msg=dom.find(".pspt_back_msg");var vCode=new verifyCode();loginFormCheckFun(formData,f_email,f_pw,f_vcode);dom.find(".refresh_vcode").bind("click",function(){vCode.refresh();return false;});dom.find("form").bind("submit",function(){formData.ready=true;form_msg.hide();f_email.trigger("blur",true);f_pw.trigger("blur",true);f_vcode.trigger("blur",true);if(formData.ready){request(formData.data,form_msg,callBack,vCode);}
return false;});vCode.bind("created",function(data){dom.find("#login_verifycode_img").append(data.img);formData.data.hidden_unique=data.uid;});vCode.bind("refresh",function(uid){formData.data.hidden_unique=uid;});vCode.create();this.dom=dom;this.focusDom=f_email;}
function loginFormCheckFun(formData,f_email,f_pw,f_vcode){f_email.bind("blur",function(event,issubmit){var val=$.trim($(this).val());var tip=$("#span_"+$(this).attr("id"));if(issubmit&&val===""){tip.html(_lang[1]);formData.ready=false;}else if(val!==""&&!REG_EMAIL.test(val)){tip.html(_lang[0]);formData.ready=false;}else{tip.html("");formData.data.email=val;}});f_pw.bind("blur",function(event,issubmit){var val=$.trim($(this).val());var tip=$("#span_"+$(this).attr("id"));if(issubmit&&val===""){tip.html(_lang[2]);formData.ready=false;}else{tip.html("");formData.data.pw=val;}});f_vcode.bind("blur",function(event,issubmit){var val=$.trim($(this).val());var tip=$("#span_"+$(this).attr("id"));if(issubmit&&val===""){tip.html(_lang[3]);formData.ready=false;}else{tip.html("");formData.data.verifycode=val;}});}
function popRegister(callBack){var formData={"ready":true,"data":{"do":"register","email":"","pw":"","pw2":"","verifycode":"","hidden_unique":""}};template='<form action="#"method="POST"name="registerForm"><fieldset id="open_regbox"class="open_regloginbox now"><p class="pspt_back_msg"></p><p class="p_item"><label class="itemtitle">您的Email地址：</label><input type="text"class="txt"id="registerEmail"name="email"maxlength="100"tabindex="1"/><span id="span_registerEmail" class="pspt_msg">&nbsp;</span><br/><em class="em_br">请填写有效的Email，我们会给这个地址发送账户信息、订单通知等。</em></p><p class="p_item"><label class="itemtitle">设置密码：</label><input type="password"class="txt"id="registerPassword"name="password"maxlength="30"tabindex="2"/><span id="span_registerPassword"class="pspt_msg">&nbsp;</span></p><p class="p_item"><label class="itemtitle">再次输入密码：</label><input type="password"class="txt"id="resetPassword"name="passwordConfirm"maxlength="30"tabindex="3"/><span id="span_resetPassword"class="pspt_msg">&nbsp;</span></p><p class="p_item"><label class="itemtitle">验证码：</label><input class="txt"type="text"autocomplete="off"id="registerVerifycode"name="verifycode"style="width:65px;"maxlength="4"tabindex="4"/><span id="register_verifycode_img"></span>&nbsp;<a href="#"class="c_b refresh_vcode">换一张</a>&nbsp;<span id="span_registerVerifycode"class="pspt_msg"></span></p><p class="p_item p_btn"><input type="submit"class="btn btn_a2"name="btn_submit"value="同意用户协议并注册"tabindex="5"/><br/><br/><a class="a_readitem"href="http://www.mbaobao.com/faq.php?id=5"target="_blank">阅读用户注册协议</a></p></fieldset></form>';var dom=$(document.createElement("div")).hide().html(template);var f_email=dom.find("#registerEmail");var f_pw=dom.find("#registerPassword");var f_pw2=dom.find("#resetPassword");var f_vcode=dom.find("#registerVerifycode");var form_msg=dom.find(".pspt_back_msg");var vCode=new verifyCode();registerFormCheckFun(formData,f_email,f_pw,f_pw2,f_vcode);dom.find(".refresh_vcode").bind("click",function(){vCode.refresh();return false;});dom.find("form").bind("submit",function(){formData.ready=true;form_msg.hide();f_email.trigger("blur",true);f_pw.trigger("blur",true);f_pw2.trigger("blur",true);f_vcode.trigger("blur",true);if(formData.ready){request(formData.data,form_msg,callBack,vCode);}
return false;});vCode.bind("created",function(data){dom.find("#register_verifycode_img").append(data.img);formData.data.hidden_unique=data.uid;});vCode.bind("refresh",function(uid){formData.data.hidden_unique=uid;});vCode.create()
this.dom=dom;this.focusDom=f_email;}
function registerFormCheckFun(formData,f_email,f_pw,f_pw2,f_vcode){f_email.bind("blur",function(event,issubmit){var val=$.trim($(this).val());var tip=$("#span_"+$(this).attr("id"));if(issubmit&&val===""){tip.html(_lang[1]);formData.ready=false;}else if(val!==""&&!REG_EMAIL.test(val)){tip.html(_lang[0]);formData.ready=false;}else if(val.length>USERNAME_MAX_LENGHT){tip.html(_lang[8]);formData.ready=false;}else if(val!==""){formData.data.email=val;_checkEmail(val,function(has){if(has){tip.html(_lang[7]);formData.ready=false;}else{tip.html("");}});}else{tip.html("");formData.data.email=val;}});f_pw.bind("blur",function(event,issubmit){var val=$.trim($(this).val());var tip=$("#span_"+$(this).attr("id"));if(issubmit&&val===""){tip.html(_lang[2]);formData.ready=false;}else{tip.html("");formData.data.pw=val;}});f_pw2.bind("blur",function(event,issubmit){var val=$.trim($(this).val());var tip=$("#span_"+$(this).attr("id"));if(issubmit&&val===""){tip.html(_lang[6]);formData.ready=false;}else if(formData.data.pw!==""&&val!=formData.data.pw){tip.html(_lang[5]);formData.ready=false;}else{tip.html("");formData.data.pw2=val;}});f_vcode.bind("blur",function(event,issubmit){var val=$.trim($(this).val());var tip=$("#span_"+$(this).attr("id"));if(issubmit&&val===""){tip.html(_lang[3]);formData.ready=false;}else{tip.html("");formData.data.verifycode=val;}});}
function popLoginAndRegister(firstShowTag){var loginContent,registerContent
var self=this;var template='<h3 id="h3_open_reglogin"><span class="span_open_login">登 录</span><span class="span_open_reg">注 册</span></h3>';this.firstShowTag=firstShowTag?firstShowTag:"login";this.callBack=function(){};this.create=function(){loginContent=new popLogin(self.callBack);registerContent=new popRegister(self.callBack);var dom=$(document.createElement("div")).append(template);dom.append(loginContent.dom).append(registerContent.dom);var loginBut=dom.find(".span_open_login");var regBut=dom.find(".span_open_reg");loginContent.dom.find(".go_register_pop").click(function(){regBut.trigger("click");return false;});loginBut.click(function(){if(!$(this).hasClass("now")){regBut.removeClass("now");registerContent.dom.hide();loginContent.dom.show();loginContent.focusDom.focus();$(this).addClass("now");}
return false;});regBut.click(function(){if(!$(this).hasClass("now")){loginBut.removeClass("now");loginContent.dom.hide();registerContent.dom.show();registerContent.focusDom.focus();$(this).addClass("now");}
return false;});if(self.firstShowTag==="login"){loginContent.dom.show();setTimeout(function(){loginContent.focusDom.focus();},200);loginBut.addClass("now");}else{registerContent.dom.show();setTimeout(function(){registerContent.focusDom.focus();},200);regBut.addClass("now");}
_pop=createPop(_opt.title,dom);}}
function request(data,msgDom,callBack,vCode){var msg=$(msgDom);$.ajax({"type":"GET","contentType":"application/x-www-form-urlencoded; charset=utf-8","url":SERVER_PATH,"dataType":"jsonp","timeout":TIMEOUT,"data":data,"success":function(json){if(json.success===0){msg.hide().html(json.msg).fadeIn("slow");vCode.refresh();}else if(json.success===1){api.user=json.data;hidePop();callBack(api.user);}},"error":function(){msg.html(_lang[4]).fadeIn("slow");}});}
function createPop(title,dom){var base_div=$(document.createElement("div")).attr({"style":"visibility:hidden;z-index:2100;position:fixed;text-align:left;width:"+_opt.width+"px;top:45%;left:50%;"+(_isIE6?"_position:absolute;_top:expression(document.documentElement.scrollTop+(document.documentElement.clientHeight-this.offsetHeight-(parseInt(this.currentStyle.marginTop,10)||0)-(parseInt(this.currentStyle.marginBottom,10)||0))/2);":"")}).html('<div class="mbbpspt_pop"><div class="opencir cir_1"></div><div class="opencir cir_2"></div><div class="opencir cir_3"></div><div class="opencir cir_4"></div><h3 class="mbbpspt_opentitle"><span class="span_opentitle"></span></h3><span class="span_close">关闭</span><div class="mbbpspt_opencont"></div><div class="opencirb cirb_1"></div><div class="opencirb cirb_2"></div><div class="opencirb cirb_3"></div><div class="opencirb cirb_4"></div></div>');base_div.find(_opt.closeClass).click(function(){hidePop();});base_div.find(_opt.titleClass).html(title);base_div.find(_opt.contentClass).append(dom);$("body").append(base_div);var t=Math.floor(base_div.height()/2);var l=Math.floor(base_div.width()/2);base_div.css({"visibility":"visible",'marginTop':-t,'marginLeft':-l,"display":"block"});lock();return base_div;}
function hidePop(){_pop.remove();unlock();_pop=null;_popContent=null;}
function lock(){var mask;if(typeof(_mask)!=="undefined"){mask=_mask;}else{_mask=$(document.createElement("div")).attr({"style":"z-index:2000;position:absolute;top:0px;left:0px;width:100%;height:100%;background:#000;filter:alpha(opacity=20);opacity:0.2;"});$('body').append(_mask);_mask.click(function(){hidePop();});if(_isIE6){_mask.append('<iframe src="about:blank" style="width:100%;height:100%;position:absolute;top:0;left:0;z-index:-1;filter:alpha(opacity=0);"></iframe>');}
mask=_mask;}
mask.height($(document).height());mask.show();}
function unlock(){if(typeof(_mask)!=="undefined"){_mask.hide();}}
api={user:null,checkEmail:_checkEmail,checkLogin:_checkLogin,login:function(callBack){var pspt_pop=new popLoginAndRegister("login");if(typeof(callBack)==="function"){pspt_pop.callBack=callBack;}
pspt_pop.create();},register:function(callBack){var pspt_pop=new popLoginAndRegister("register");if(typeof(callBack)==="function"){pspt_pop.callBack=callBack;}
pspt_pop.create();}};return api;})();function verifyCode(){var VERIFYCODE_PATH="http://login.mbaobao.com/picCode.checkcode";var UNIQUE_ID_PATH="http://login.mbaobao.com/checkCode.json";this.vcImg=null;var _self=this;this.create=function(){getUniqueId(function(uid){var img=$(document.createElement("img")).attr({"src":VERIFYCODE_PATH+"?unique_id="+uid,"width":58,"height":21,"alt":"看不到验证码？点击重新换一个！","title":"看不到验证码？点击重新换一个！","style":"cursor:pointer"}).click(function(){_self.refresh();});_self.vcImg=img;_self.trigger("created",{"img":img.get(0),"uid":uid});});};this.refresh=function(){var vcImg=_self.vcImg;if(vcImg!==null){getUniqueId(function(uid){vcImg.attr({"src":VERIFYCODE_PATH+"?unique_id="+uid});_self.trigger("refresh",uid);});}};function getUniqueId(callBack){$.ajax({"type":"GET","url":UNIQUE_ID_PATH,"dataType":"jsonp","success":function(data){callBack(data.unique_id);}});}}
verifyCode.prototype=new eventModel();function eventModel(){this.bind=function(evt,fun){if(typeof(evt)!=="string"||evt===""||typeof(fun)!=="function"){return false;}
var evts=evt.split(",");for(var i=0;i<evts.length;i++){var evt_t=evts[i];if(typeof(this["on"+evt_t])==="undefined"){this["on"+evt_t]=[];}
var events=this["on"+evt_t];if(events&&typeof(events)=="function"){this["on"+evt_t]=[events];events=this["on"+evt_t];}
events.push(fun);}};this.unbind=function(evt,fun){var evts=evt.split(",");for(var n=0;i<evts.length;n++){var evt_t=evts[n];var events=this["on"+evt_t];if(events&&typeof(events)=="function"){events=[events];}
if(fun){for(var i=0;i<events.length;i++){if(events[i]==fun){events.splice(i,1);}}}else{this["on"+evt_t]=[];}}};this.trigger=function(evt,eventArgs){if(typeof(evt)!=="string"||evt===""){return;}
eventArgs=eventArgs||{};var events=this["on"+evt];if(typeof(events)!=="undefined"){var len=events.length;for(var i=0;i<len;i++){var evthander=events[i];evthander(eventArgs);}}};}